org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx6g"
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.incremental.js=true
kotlin.js.webpack.memoryLimit=4096
kotlin.js.yarn=true
android.useAndroidX=true